In [1]:
import cv2
import numpy as np
from PIL import Image
img=cv2.imread("images/1.jpg")

In [4]:
b=img[:,:,:1]
g=img[:,:,1:2]
r=img[:,:,2:]

In [5]:
print(b)
print(b.shape)

[[[126]
  [126]
  [126]
  ...
  [145]
  [145]
  [145]]

 [[126]
  [126]
  [126]
  ...
  [145]
  [145]
  [145]]

 [[126]
  [126]
  [126]
  ...
  [145]
  [145]
  [145]]

 ...

 [[153]
  [153]
  [153]
  ...
  [159]
  [159]
  [159]]

 [[153]
  [153]
  [153]
  ...
  [159]
  [159]
  [159]]

 [[153]
  [153]
  [153]
  ...
  [159]
  [159]
  [159]]]
(540, 960, 1)


In [7]:
np.concatenate((b,g,r),axis=2)

array([[[126, 145, 152],
        [126, 145, 152],
        [126, 145, 152],
        ...,
        [145, 166, 174],
        [145, 166, 174],
        [145, 166, 174]],

       [[126, 145, 152],
        [126, 145, 152],
        [126, 145, 152],
        ...,
        [145, 166, 174],
        [145, 166, 174],
        [145, 166, 174]],

       [[126, 145, 152],
        [126, 145, 152],
        [126, 145, 152],
        ...,
        [145, 166, 174],
        [145, 166, 174],
        [145, 166, 174]],

       ...,

       [[153, 172, 185],
        [153, 172, 185],
        [153, 172, 185],
        ...,
        [159, 179, 184],
        [159, 179, 184],
        [159, 179, 184]],

       [[153, 172, 185],
        [153, 172, 185],
        [153, 172, 185],
        ...,
        [159, 179, 184],
        [159, 179, 184],
        [159, 179, 184]],

       [[153, 172, 185],
        [153, 172, 185],
        [153, 172, 185],
        ...,
        [159, 179, 184],
        [159, 179, 184],
        [159, 179, 184]]

In [2]:
cv2.imshow("",img)
cv2.waitKey(0)

-1